# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daily virtual life
email: dario.doerflinger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here I'll blog about tech passions with VMware focus...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://virtualfrog.github.io" # the base hostname & protocol for your site
twitter_username: virtual_frog
github_username:  virtualFrog
clarity_header_iconshape: dna
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-mentions
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-feed

# Build settings
markdown: kramdown

exclude: ['node_modules','package.json','.settings','.project','about_english.md','404.md']
compress_html:
  blanklines: true

sass:
  style: :expanded # You might prefer to minify using :compressed
